[project]
name = "supportiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "dspy>=2.6.27",
    "jupyter>=1.1.1",
    "ruff>=0.12.2",
    "scikit-learn>=1.7.0",
]
